# Define the services used in the application
services:
  # Configuration for the web service, where the FastAPI app is deployed
  web:
    build: .                             # Build the Docker image using the Dockerfile in the current directory
    volumes:                             
      - ./:/usr/src/app/                # Mount the current directory to /usr/src/app in the container
    ports:
      - "${WEB_PORT}:8000"              # Map port 8000 of the container to port 8443 on the host
    restart: always

  # Configuration for the Prometheus monitoring service
  prometheus:
    image: prom/prometheus              # Use the official Prometheus image from Docker Hub
    container_name: prometheus          # Name the container as 'prometheus'
    ports:
      - "${PROMETHEUS_PORT}:9090"       # Map port 9090 of the container to port 9090 on the host
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml # Mount the Prometheus config file
      - prometheus_data:/prometheus  
    command:
      - '--config.file=/etc/prometheus/prometheus.yml' # Command to specify the config file location
      - '--storage.tsdb.path=/prometheus' 
    restart: always

  # Configuration for the Grafana service
  grafana:
    image: grafana/grafana              # Use the official Grafana image from Docker Hub
    container_name: grafana             # Name the container as 'grafana'
    ports:
      - "${GRAFANA_PORT}:3000"          # Map port 3000 of the container to port 3000 on the host
    volumes:
      - grafana_data:/var/lib/grafana   # Mount the Grafana data volume for persistence
    restart: always

# Define the volumes used by Prometheus and Grafana for data persistence
volumes:
  prometheus_data:                       # Volume for Prometheus data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus_data          # Location on the host machine to store Prometheus data
  grafana_data:                          # Volume for Grafana data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana_data             # Location on the host machine to store Grafana data

# Define the default network settings
networks:
  default: 
    name: 3DBluePrint_fastapi            # Name the default network used by all services
